spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/leafage
    username: postgres
    password: zx110119
    driver-class-name: org.postgresql.Driver

app:
  base-uri: http://127.0.0.1:9000